one big chunk of code in a feature branch
Elhambasir/review-coding-partner-project pull request #1
Opened 2023-04-03 17:46 UTC by Elhambasir

This pull request is made for the coding partner's project review

2023-04-05 07:04 UTC, Lul-Abdifan requested changes
Hello @Elhambasir, Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There is some hindrance that make me not to review your project.

2023-04-05 07:04 UTC, Lul-Abdifan commented on README.md
> +[Live Demo Link](https://Elhambasir.github.io/To-Do-List/)
- Nice to have a Live Demo, Could you please fix this line of code? It is directing me to your web. or Add server.js file in order review your project.
![image](https://user-images.githubusercontent.com/86189460/230002729-3071f42b-a9f9-4b9a-8060-3b32b8678d2a.png)

2023-04-05 07:36 UTC, Elhambasir commented on README.md
> +[Live Demo Link](https://Elhambasir.github.io/To-Do-List/)
Thank you I will fix that as soon as possible

2023-04-07 09:29 UTC, Lul-Abdifan approved these changes
Hello @Elhambasir, I appreciate your Job. Your project is complete! There is nothing else to say other than... it's time to merge it :clap: :clap: :clap: 
Congratulations! 

![](https://e0.365dm.com/23/02/1600x900/skysports-man-utd-erik-ten-hag_6067873.jpg?20230223231928)

## Highlights
✅ Good Implementation 
✅ Professional PR
✅ Professional Commits
✅ No Linters error

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-07 09:29 UTC, Lul-Abdifan commented on src/index.html
> +        <input type="text" name="job" class="input-job" placeholder="Add to your list">
Kindly add a label to the form input elements to ensure you comply with HTML best practices, i.e accessibility. :smile:

2023-04-07 09:29 UTC, Lul-Abdifan commented on src/index.js
> +  document.querySelectorAll('.checkbox').forEach((element) => {
-  Could you please initiate all variables at the beginning of the various scopes in order to keep JavaScript best practices

2023-04-07 09:29 UTC, Lul-Abdifan commented on src/index.js
> +document.querySelectorAll('.checkbox').forEach((element) => {
- Could you please also look at this?

2023-04-07 09:29 UTC, Lul-Abdifan commented on src/index.js
> +    document.querySelectorAll('.checkbox').forEach((element) => {
- Could you please also look at this?

2023-04-07 09:29 UTC, Lul-Abdifan commented on src/index.js
> +document.querySelectorAll('.checkbox').forEach((element) => {
- Could you please also look at this?

2023-04-07 11:44 UTC, merged